# Gradle
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
# Mod Metadata
group=dev.sisby
user=sisby-folk
slug=surveyalot
modId=surveyalot
modName=Surveyalot
modDescription=Surveyor map landmarks for chunk claim mods!
authors=Sisby folk
contributors=
license=EUPL-1.2
# Mod Version
modVersion=0.1.6
# Branch Metadata
branchName=1.20
tagBranch=1.20
compatibleVersions=1.20.1, 1.21.1, 1.21.8
compatibleLoaders=fabric, quilt
